twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic   : /cmd_vel_teleop
        timeout : 0.5
        priority: 1
      joystick: 
        topic   : /cmd_vel_joy
        timeout : 0.5
        priority: 3
      emergency: 
        topic   : /cmd_vel_emerg
        timeout : 0.0
        priority: 4
      auton: 
        topic   : /cmd_vel_auton
        timeout : 0.5
        priority: 2